### ISSUE TITLE
Crash when trying to attach lead to cow

### ISSUE THREAD

**Issue by DaedalusProspect** [ProjectZulu/Project-Zulu#103]
Hey guys,

Currently hitting a crash whenever I or anyone else on my server tries to attach a lead to a cow. This crash is client side only, and doesnt affect the server at all.

Tried removing battlegear as well and the issue persists until Project Zulu is removed. When you load back up the client, sometimes the lead will then be attached to the cow.

kcauldron 1492.152
Minecraft version 1.7.10

Crash log below:
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 10/6/15 12:38 PM
Description: Unexpected error

java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
    at com.google.common.base.Absent.get(Absent.java:47)
    at com.stek101.projectzulu.common.core.EventHookContainerClass.onEntityInteract(EventHookContainerClass.java:191)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_465_EventHookContainerClass_onEntityInteract_EntityInteractEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at mods.battlegear2.api.core.BattlegearUtils.interactWith(BattlegearUtils.java:511)
    at net.minecraft.entity.player.EntityPlayer.func_70998_m(Unknown Source)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78768_b(Unknown Source)
    at net.minecraft.client.Minecraft.func_147121_ag(Unknown Source)
    at net.minecraft.client.Minecraft.func_71407_l(Unknown Source)
    at net.minecraft.client.Minecraft.func_71411_J(Unknown Source)
    at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.google.common.base.Absent.get(Absent.java:47)
    at com.stek101.projectzulu.common.core.EventHookContainerClass.onEntityInteract(EventHookContainerClass.java:191)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_465_EventHookContainerClass_onEntityInteract_EntityInteractEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at mods.battlegear2.api.core.BattlegearUtils.interactWith(BattlegearUtils.java:511)
    at net.minecraft.entity.player.EntityPlayer.func_70998_m(Unknown Source)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78768_b(Unknown Source)
    at net.minecraft.client.Minecraft.func_147121_ag(Unknown Source)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [GCEntityClientPlayerMP['Zammis'/372627, l='MpServer', x=3.54, y=65.62, z=907.61]]
    Chunk stats: MultiplayerChunkCache: 399, 399
    Level seed: 0
    Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-30,73,738), Chunk: (at 2,4,2 in -2,46; contains blocks -32,0,736 to -17,255,751), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
    Level time: 14789431 game time, 15144220 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 57 total; [GCEntityOtherPlayerMP['Shortie27'/371740, l='MpServer', x=-7.21, y=74.34, z=730.80], EntitySheep['Sheep'/439309, l='MpServer', x=29.94, y=72.00, z=844.03], EntityTrail['unknown'/526, l='MpServer', x=3.54, y=65.62, z=907.61], GCEntityOtherPlayerMP['Shortie27'/371740, l='MpServer', x=4.75, y=64.00, z=699.50], GCEntityOtherPlayerMP['Shortie27'/371740, l='MpServer', x=15.06, y=64.00, z=714.77], GCEntityClientPlayerMP['Zammis'/372627, l='MpServer', x=3.54, y=65.62, z=907.61], GCEntityOtherPlayerMP['Shortie27'/371740, l='MpServer', x=-36.31, y=100.00, z=767.69], GCEntityOtherPlayerMP['Shortie27'/371740, l='MpServer', x=14.02, y=64.00, z=702.49], GCEntityOtherPlayerMP['Shortie27'/371740, l='MpServer', x=1.67, y=64.00, z=691.33], EntityZombie['Zombie'/912679, l='MpServer', x=48.46, y=-1.62, z=32.39], EntitySkeleton['Skeleton'/441386, l='MpServer', x=15.09, y=59.29, z=857.70], GCEntityOtherPlayerMP['Shortie27'/371740, l='MpServer', x=11.88, y=71.72, z=699.47], EntityZombie['Zombie'/912672, l='MpServer', x=48.46, y=-1.62, z=29.39], EntityCreeper['Creeper'/441384, l='MpServer', x=11.30, y=59.04, z=853.75], EntityZombie['Zombie'/912691, l='MpServer', x=48.46, y=-1.62, z=34.39], GCEntityOtherPlayerMP['Shortie27'/371740, l='MpServer', x=44.03, y=70.00, z=704.44], EntityItem['item.item.leash'/441934, l='MpServer', x=12.25, y=70.13, z=896.09], EntityZombie['Zombie'/912708, l='MpServer', x=48.46, y=-1.62, z=37.39], EntityCow['Cow'/439628, l='MpServer', x=11.69, y=64.00, z=908.50], EntityHat['unknown'/75, l='MpServer', x=3.54, y=65.62, z=907.61], EntityCow['Cow'/439629, l='MpServer', x=4.19, y=64.00, z=910.88], EntityLavaMonster['Lava Monster'/445526, l='MpServer', x=39.50, y=8.00, z=848.50], EntityCreeper['Creeper'/445527, l='MpServer', x=29.50, y=22.00, z=869.50], GCEntityOtherPlayerMP['Shortie27'/371740, l='MpServer', x=-32.46, y=67.00, z=740.48], EntitySkeleton['Skeleton'/445523, l='MpServer', x=11.50, y=33.00, z=884.50], EntityZombie['Zombie'/912720, l='MpServer', x=55.46, y=-1.62, z=29.39], EntityLavaMonster['Lava Monster'/445295, l='MpServer', x=-3.50, y=6.63, z=907.50], EntitySkeleton['Skeleton'/445551, l='MpServer', x=13.50, y=25.00, z=872.50], GCEntityOtherPlayerMP['Shortie27'/371740, l='MpServer', x=10.59, y=71.72, z=731.50], EntityItem['item.item.leash'/445813, l='MpServer', x=6.06, y=69.13, z=895.06], GCEntityOtherPlayerMP['Shortie27'/371740, l='MpServer', x=-43.06, y=66.00, z=769.94], GCEntityOtherPlayerMP['Shortie27'/371740, l='MpServer', x=18.97, y=71.41, z=731.41], GCEntityOtherPlayerMP['Shortie27'/371740, l='MpServer', x=11.97, y=69.00, z=894.25], EntityLavaMonster['Lava Monster'/445580, l='MpServer', x=43.50, y=5.62, z=845.50], EntitySkeleton['Skeleton'/444810, l='MpServer', x=-32.16, y=68.00, z=879.22], GCEntityOtherPlayerMP['Shortie27'/371740, l='MpServer', x=11.75, y=64.00, z=712.71], EntityCreeper['Creeper'/444808, l='MpServer', x=50.09, y=80.00, z=862.66], EntitySpider['Spider'/855196, l='MpServer', x=28.67, y=-50.70, z=-22.23], EntityPig['Pig'/439454, l='MpServer', x=4.64, y=69.00, z=893.81], EntityZombie['Zombie'/444574, l='MpServer', x=1.50, y=25.00, z=885.50], GCEntityOtherPlayerMP['Shortie27'/371740, l='MpServer', x=-25.31, y=74.00, z=631.43], GCEntityOtherPlayerMP['Shortie27'/371740, l='MpServer', x=-5.97, y=67.72, z=701.16], GCEntityOtherPlayerMP['Shortie27'/371740, l='MpServer', x=12.50, y=64.00, z=705.03], GCEntityOtherPlayerMP['Shortie27'/371740, l='MpServer', x=46.09, y=66.00, z=705.38], GCEntityOtherPlayerMP['Shortie27'/371740, l='MpServer', x=10.59, y=71.72, z=731.50], EntityPainting['Painting'/409561, l='MpServer', x=143.00, y=69.00, z=757.06], GCEntityOtherPlayerMP['Shortie27'/371740, l='MpServer', x=11.04, y=64.00, z=716.37], EntityKiwi['Kiwi'/434365, l='MpServer', x=-8.25, y=76.00, z=842.41], EntityPainting['Painting'/409562, l='MpServer', x=143.00, y=69.00, z=757.06], EntityCow['Cow'/439766, l='MpServer', x=32.69, y=65.00, z=917.56], EntityWoodpecker['Woodpecker'/440286, l='MpServer', x=53.59, y=67.53, z=968.41], GCEntityOtherPlayerMP['Shortie27'/371740, l='MpServer', x=-36.31, y=98.00, z=767.69], EntityLavaMonster['Lava Monster'/445156, l='MpServer', x=52.50, y=5.21, z=854.50], EntityCaveSpider['Cave Spider'/855526, l='MpServer', x=8.01, y=-46.62, z=-22.70], EntityBeetleAS['Small Beetle'/440821, l='MpServer', x=-26.47, y=71.00, z=871.78], EntityZombie['Zombie'/817144, l='MpServer', x=-38.60, y=-35.62, z=1.47], GCEntityOtherPlayerMP['Shortie27'/371740, l='MpServer', x=-5.49, y=65.00, z=756.14]]
    Retry entities: 0 total; []
    Server brand: kcauldron,cauldron,craftbukkit,mcpc,fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Unknown Source)
    at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_31, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 618175920 bytes (589 MB) / 2213056512 bytes (2110 MB) up to 8482586624 bytes (8089 MB)
    JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G -XX:MaxPermSize=256m -XX:ParallelGCThreads=4 -XX:+UseParNewGC
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 Optifine OptiFine_1.7.10_HD_C1 120 mods loaded, 120 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1492-1.7.10.jar) 
    UCHIJA  Forge{10.13.4.1492} [Minecraft Forge](forge-1.7.10-10.13.4.1492-1.7.10.jar) 
    UCHIJA  CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHIJA  ivtoolkit{IvToolkit} [1.2](minecraft.jar) 
    UCHIJA  Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
    UCHIJA  NotEnoughItems{1.0.5.118} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
    UCHIJA  OpenModsCore{0.8} [OpenModsCore](minecraft.jar) 
    UCHIJA  <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJA  psychedelicraftcore{1.4} [Psychedelicraft Core](minecraft.jar) 
    UCHIJA  FastCraft{1.22} [FastCraft](fastcraft-1.22-ctest14.jar) 
    UCHIJA  dynamicswordskills{1.7.10-1.6.5} [Dynamic Sword Skills](1.7.10-dynamicswordskills-1.6.5.jar) 
    UCHIJA  battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye](1.7.10-MB_Battlegear2-Bullseye-1.0.8.1.jar) 
    UCHIJA  CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCHIJA  BuildCraft|Core{7.0.23} [BuildCraft](buildcraft-7.0.23.jar) 
    UCHIJA  BuildCraft|Energy{7.0.23} [BC Energy](buildcraft-7.0.23.jar) 
    UCHIJA  GalacticraftCore{3.0.11} [Galacticraft Core](GalacticraftCore-1.7-3.0.11.333.jar) 
    UCHIJA  SpaceCore{4.1.9} [4Space Core](4Space-4.1.9.jar) 
    UCHIJA  ExoCore{0.1.2} [4Space Exoplanets Core](4Space-4.1.9.jar) 
    UCHIJA  ExoElipse{0.1.2} [4Space Exoplanets Elipse](4Space-4.1.9.jar) 
    UCHIJA  SpaceCallisto{4.1.9} [4Space Callisto](4Space-4.1.9.jar) 
    UCHIJA  SpaceEuropa{4.1.9} [4Space Europa](4Space-4.1.9.jar) 
    UCHIJA  SpaceVenus{4.1.9} [4Space Venus](4Space-4.1.9.jar) 
    UCHIJA  SpaceIo{4.1.9} [4Space Io](4Space-4.1.9.jar) 
    UCHIJA  SpaceMercury{4.1.9} [4Space Mercury](4Space-4.1.9.jar) 
    UCHIJA  SpacePluto{4.1.9} [4Space Pluto](4Space-4.1.9.jar) 
    UCHIJA  betterrecords{1.7.10-1.1.9} [Better Records](betterrecords-1.7.10-1.1.9.jar) 
    UCHIJA  BiblioCraft{1.11.1} [BiblioCraft](BiblioCraft[v1.11.1][MC1.7.10].jar) 
    UCHIJA  BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1396-universal.jar) 
    UCHIJA  BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition](BiblioWoods[BiomesOPlenty][v1.9].jar) 
    UCHIJA  Forestry{3.6.6.24} [Forestry for Minecraft](forestry_1.7.10-3.6.6.24.jar) 
    UCHIJA  BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition](BiblioWoods[Forestry][v1.7].jar) 
    UCHIJA  bigtrees{1.7.2b} [The BigTrees Mod](BigTrees-172b-forge1060.jar) 
    UCHIJA  Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJA  Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHIJA  Botania{r1.7-223} [Botania](Botania r1.7-223.jar) 
    UCHIJA  BuildCraft|Factory{7.0.23} [BC Factory](buildcraft-7.0.23.jar) 
    UCHIJA  BuildCraft|Silicon{7.0.23} [BC Silicon](buildcraft-7.0.23.jar) 
    UCHIJA  BuildCraft|Transport{7.0.23} [BC Transport](buildcraft-7.0.23.jar) 
    UCHIJA  BuildCraft|Builders{7.0.23} [BC Builders](buildcraft-7.0.23.jar) 
    UCHIJA  BuildCraft|Robotics{7.0.23} [BC Robotics](buildcraft-7.0.23.jar) 
    UCHIJA  CarpentersBlocks{3.3.7} [Carpenter's Blocks](Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
    UCHIJA  Railcraft{9.7.0.0} [Railcraft](Railcraft_1.7.10-9.7.0.0.jar) 
    UCHIJA  ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJA  chisel{2.5.1.44} [Chisel 2](Chisel2-2.5.1.44.jar) 
    UCHIJA  chococraft{4.1.5} [Clienthax's ChocoCraft](ChocoCraft-4.1.5.jar) 
    UCHIJA  chocolateQuest{1.0} [Chocolate Quest](chocolateQuest-1.7.10-1.0.jar) 
    UCHIJA  customnpcs{1.7.10d} [CustomNpcs](CustomNPCs_1.7.10d.jar) 
    UCHIJA  dynamictanks{1.0} [Dynamic Liquid Tanks 2.1](dynamictanks-1.1.04.jar) 
    UCHIJA  Enchiridion{1.1} [Enchiridion](Enchiridion-1.7.X-1.2b.jar) 
    UCHIJA  EnderStorage{1.4.7.37} [EnderStorage](EnderStorage-1.7.10-1.4.7.37-universal.jar) 
    UCHIJA  exoticbirds{1.0} [Exotic Birds](Exotic Birds 1.0.2b-1.7.10.jar) 
    UCHIJA  ForgeEssentialsClient{1.4.3} [Forge Essentials Client Addon](forgeessentials-1.7.10-1.4.3.970-client.jar) 
    UCHIJA  fossil{1.7.10 Build 7.2.1} [Fossils and Archeology Revival](Fossils_Archeology_Revival-1.7.10_Build-7.2.1.jar) 
    UCHIJA  GalacticraftMars{3.0.11} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.11.333.jar) 
    UCHIJA  GardenContainers{1.7.10-1.6.8} [Garden Containers](GardenStuff-1.7.10-1.6.8.jar) 
    UCHIJA  GardenCore{1.7.10-1.6.8} [Garden Core](GardenStuff-1.7.10-1.6.8.jar) 
    UCHIJA  GardenStuff{1.7.10-1.6.8} [Garden Stuff](GardenStuff-1.7.10-1.6.8.jar) 
    UCHIJA  GardenTrees{1.7.10-1.6.8} [Garden Trees](GardenStuff-1.7.10-1.6.8.jar) 
    UCHIJA  GraveStone{2.12.3} [GraveStone](GraveStone-2.12.4.jar) 
    UCHIJA  Growthcraft{2.2.2} [Growthcraft](growthcraft-2.2.2-complete.jar) 
    UCHIJA  Growthcraft|Cellar{2.2.2} [Growthcraft Cellar](growthcraft-2.2.2-complete.jar) 
    UCHIJA  Growthcraft|Apples{2.2.2} [Growthcraft Apples](growthcraft-2.2.2-complete.jar) 
    UCHIJA  Growthcraft|Bamboo{2.2.2} [Growthcraft Bamboo](growthcraft-2.2.2-complete.jar) 
    UCHIJA  Growthcraft|Bees{2.2.2} [Growthcraft Bees](growthcraft-2.2.2-complete.jar) 
    UCHIJA  Growthcraft|Fishtrap{2.2.2} [Growthcraft Fishtrap](growthcraft-2.2.2-complete.jar) 
    UCHIJA  Growthcraft|Grapes{2.2.2} [Growthcraft Grapes](growthcraft-2.2.2-complete.jar) 
    UCHIJA  Growthcraft|Hops{2.2.2} [Growthcraft Hops](growthcraft-2.2.2-complete.jar) 
    UCHIJA  Growthcraft|Rice{2.2.2} [Growthcraft Rice](growthcraft-2.2.2-complete.jar) 
    UCHIJA  iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
    UCHIJA  Hats{4.0.1} [Hats](Hats-4.0.1.jar) 
    UCHIJA  HatStand{4.0.0} [HatStand](HatStand-4.0.0.jar) 
    UCHIJA  inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UCHIJA  IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCHIJA  Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJA  JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) 
    UCHIJA  journeymap{@JMVERSION@} [JourneyMap](journeymap-1.7.10-5.1.0-unlimited.jar) 
    UCHIJA  jcanimation{1.2.4} [JCAnimationAPI](JurassiCraft-1.4.5.jar) 
    UCHIJA  llibrary{0.3.4-1.7.10} [LLibrary](LLibrary-0.3.4-1.7.10.jar) 
    UCHIJA  jurassicraft{1.4.5} [JurassiCraft](JurassiCraft-1.4.5.jar) 
    UCHIJA  LavaMonsters{2.2.1} [Lava Monsters](LavaMonsters-1.7.10-2.2.1.jar) 
    UCHIJA  LotsOfFood{1.7.10} [Lots of Food](Lots of Food-1.7.10 v7.jar) 
    UCHIJA  magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops](magicalcrops-1.7.2-0.11.jar) 
    UCHIJA  RadixCore{2.0.3} [RadixCore](RadixCore-1.7.10-2.0.3-universal.jar) 
    UCHIJA  MCA{1.7.10-5.0.7.2} [Minecraft Comes Alive](MCA-1.7.10-5.0.7.2-universal.jar) 
    UCHIJA  moreplayermodels{1.7.10b} [MorePlayerModels](MorePlayerModels_1.7.10b.jar) 
    UCHIJA  cfm{3.4.8} [§9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.8%281.7.10%29.jar) 
    UCHIJA  recipehandler{1.7.10} [NoMoreRecipeConflict](NoMoreRecipeConflict-0.3%281.7.10%29.jar) 
    UCHIJA  Oceancraft{1.4.1} [Oceancraft](Oceancraft-1.4.1.jar) 
    UCHIJA  OpenMods{0.8} [OpenMods](OpenModsLib-1.7.10-0.8.jar) 
    UCHIJA  OpenBlocks{1.4.4} [OpenBlocks](OpenBlocks-1.7.10-1.4.4.jar) 
    UCHIJA  harvestcraft{1.7.10j} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10j.jar) 
    UCHIJA  plantmegapack{4.28} [Plant Mega Pack](plantmegapack-4.28-1.7.10-1492.jar) 
    UCHIJA  projectbench{0.5.0} [Project Bench Updated](ProjectBench-Update-1.7.10-0.5.jar) 
    UCHIJA  MrTJPCoreMod{1.1.0.31} [MrTJPCore](MrTJPCore-1.1.0.31-universal.jar) 
    UCHIJA  ProjRed|Core{4.7.0pre9.92} [ProjectRed Core](ProjectRed-1.7.10-4.7.0pre9.92-Base.jar) 
    UCHIJA  ProjRed|Transmission{4.7.0pre9.92} [ProjectRed Transmission](ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
    UCHIJA  ProjRed|Transportation{4.7.0pre9.92} [ProjectRed Transportation](ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
    UCHIJA  ProjRed|Exploration{4.7.0pre9.92} [ProjectRed Exploration](ProjectRed-1.7.10-4.7.0pre9.92-World.jar) 
    UCHIJA  ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    UCHIJA  ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
    UCHIJA  ProjRed|Compatibility{4.7.0pre9.92} [ProjectRed Compatibility](ProjectRed-1.7.10-4.7.0pre9.92-Compat.jar) 
    UCHIJA  ProjRed|Integration{4.7.0pre9.92} [ProjectRed Integration](ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
    UCHIJA  ProjRed|Fabrication{4.7.0pre9.92} [ProjectRed Fabrication](ProjectRed-1.7.10-4.7.0pre9.92-Fabrication.jar) 
    UCHIJA  ProjRed|Illumination{4.7.0pre9.92} [ProjectRed Illumination](ProjectRed-1.7.10-4.7.0pre9.92-Lighting.jar) 
    UCHIJA  ProjRed|Expansion{4.7.0pre9.92} [ProjectRed Expansion](ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
    UCHIJA  ProjectZulu|Core{1.7.10-1.4c2} [Project Zulu](ProjectZulu-1.7.10-1.4c2.jar) 
    UCHIJA  psychedelicraft{1.5.2} [Psychedelicraft](Psychedelicraft-1.5.2.jar) 
    UCHIJA  Roguelike{1.3.6.3} [Roguelike Dungeons](roguelike-1.7.10-1.3.6.3.jar) 
    UCHIJA  RopesPlus{1.6.4} [Ropes+](RopePlus-1.7.10.jar) 
    UCHIJA  AS_Ruins{15.1} [Ruins Spawning System](Ruins-1.7.10.jar) 
    UCHIJA  simplypaths{1.7.10-1.0.0} [Simply Paths](simplypaths-1.1.1.jar) 
    UCHIJA  foxlib{1.7.10-0.7.0} [FoxLib](FoxLib-1.7.10-0.7.0.jar) 
    UCHIJA  Tails{1.7.10-1.3.1} [Tails](Tails-1.7.10-1.3.1.jar) 
    UCHIJA  witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar) 
    UCHIJA  McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJA  ForgeRelocation{0.0.1.4} [ForgeRelocation](ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
    UCHIJA  MCFrames{1.0} [MCFrames](ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
    UCHIJA  RelocationFMP{0.0.1.2} [RelocationFMP](ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
    UCHIJA  ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1062.1004' Renderer: 'AMD Radeon R7 200 Series'
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    CoFHCore: -[1.7.10]3.0.3-303
    ThermalFoundation: -[1.7.10]1.2.0-102
    ThermalExpansion: -[1.7.10]4.0.3B1-218
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8
    Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
    Launched Version: 1.7.10-Forge10.13.4.1492-1.7.10
    LWJGL: 2.9.1
    OpenGL: AMD Radeon R7 200 Series GL version 4.5.13399 Compatibility Profile Context 15.200.1062.1004, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by soultek101** [comment]
Thank you for reporting this. I'm planning on getting back to MC modding soon. I'll check on this as soon as I can.

**Comment by DaedalusProspect** [comment]
As an update, the bug seems to extend to interacting with cows. As if you try to feed them wheat, you get the same error as above. 

But good to hear, I appreciate the support. It's nothing major on our server so were not in a rush for a fix. Thanks!
