### ISSUE TITLE
Coconut Seed crash

### ISSUE THREAD

**Issue by Nobodysme** [ProjectZulu/Project-Zulu#90]
when crafting a seed (with wooden s. and whole Coconut game crashes... 

Error:

Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException: -1
    at net.minecraft.item.ItemStack.func_77980_a(ItemStack.java:383)
    at net.minecraft.inventory.SlotCrafting.func_75208_c(SlotCrafting.java:53)
    at net.minecraft.inventory.SlotCrafting.func_75210_a(SlotCrafting.java:48)
    at net.minecraft.inventory.Slot.func_75220_a(Slot.java:45)
    at net.minecraft.inventory.ContainerWorkbench.func_82846_b(SourceFile:88)
    at net.minecraft.inventory.Container.func_75144_a(SourceFile:193)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:289)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:256)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1577)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:914)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:833)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.item.ItemStack.func_77980_a(ItemStack.java:383)
    at net.minecraft.inventory.SlotCrafting.func_75208_c(SlotCrafting.java:53)
    at net.minecraft.inventory.SlotCrafting.func_75210_a(SlotCrafting.java:48)
    at net.minecraft.inventory.Slot.func_75220_a(Slot.java:45)
    at net.minecraft.inventory.ContainerWorkbench.func_82846_b(SourceFile:88)
    at net.minecraft.inventory.Container.func_75144_a(SourceFile:193)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:289)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:256)

-- Affected screen --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiCrafting

**Comment by Crudedragos** [comment]
Fixed in Project Zulu v1.2.8.3.

Thank you for reporting.
