### ISSUE TITLE
Failed to load texture

### ISSUE THREAD

**Issue by serhiicherepanov** [ProjectZulu/Project-Zulu#98]
Hi, 

Armor textures are not rendered on ProjectZulu-1.7.10-1.3f.jar

log here:

```
> [09:19:32] [Client thread/WARN]: Failed to load texture: projectzulublock:armor_sets/reddesertcloth_1.png
> java.io.FileNotFoundException: projectzulublock:armor_sets/reddesertcloth_1.png
>   at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
>   at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SourceFile:55) ~[brg.class:?]
>   at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:29) ~[bpu.class:?]
>   at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72) [bqf.class:?]
>   at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(SourceFile:40) [bqf.class:?]
>   at net.minecraft.client.renderer.entity.Render.func_110776_a(SourceFile:51) [bno.class:?]
>   at net.minecraft.client.renderer.entity.RenderPlayer.func_77032_a(RenderPlayer.java:67) [bop.class:?]
>   at net.minecraft.client.renderer.entity.RenderPlayer.func_77032_a(RenderPlayer.java:491) [bop.class:?]
>   at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:157) [boh.class:?]
>   at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:158) [bop.class:?]
>   at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521) [bop.class:?]
>   at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293) [bnn.class:?]
>   at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276) [bnn.class:?]
>   at net.minecraft.client.gui.inventory.GuiInventory.func_147046_a(SourceFile:91) [bfu.class:?]
>   at net.minecraft.client.gui.inventory.GuiInventory.func_146976_a(SourceFile:60) [bfu.class:?]
>   at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78) [bex.class:?]
>   at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38) [bfo.class:?]
>   at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47) [bfu.class:?]
>   at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061) [blt.class:?]
>   at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990) [bao.class:?]
>   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
>   at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_67]
>   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_67]
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_67]
>   at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_67]
>   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
>   at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
> [09:19:32] [Client thread/WARN]: Failed to load texture: projectzulublock:armor_sets/ironscale_2.png
> java.io.FileNotFoundException: projectzulublock:armor_sets/ironscale_2.png
>   at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
>   at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SourceFile:55) ~[brg.class:?]
>   at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:29) ~[bpu.class:?]
>   at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72) [bqf.class:?]
>   at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(SourceFile:40) [bqf.class:?]
>   at net.minecraft.client.renderer.entity.Render.func_110776_a(SourceFile:51) [bno.class:?]
>   at net.minecraft.client.renderer.entity.RenderPlayer.func_77032_a(RenderPlayer.java:67) [bop.class:?]
>   at net.minecraft.client.renderer.entity.RenderPlayer.func_77032_a(RenderPlayer.java:491) [bop.class:?]
>   at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:157) [boh.class:?]
>   at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:158) [bop.class:?]
>   at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521) [bop.class:?]
>   at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293) [bnn.class:?]
>   at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276) [bnn.class:?]
>   at net.minecraft.client.gui.inventory.GuiInventory.func_147046_a(SourceFile:91) [bfu.class:?]
>   at net.minecraft.client.gui.inventory.GuiInventory.func_146976_a(SourceFile:60) [bfu.class:?]
>   at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78) [bex.class:?]
>   at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38) [bfo.class:?]
>   at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47) [bfu.class:?]
>   at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061) [blt.class:?]
>   at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990) [bao.class:?]
>   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
>   at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_67]
>   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_67]
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_67]
>   at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_67]
>   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
>   at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
```

**Comment by soultek101** [comment]
Yes, this issue was reported to me about a week ago. My apologies for the inconvenience. The fix will come out by next week with the release of PZ 1.4.
